Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,18 +38,27 @@ jobs:
     env: 
       base_url: "https://eu-api.contentstack.com"
       default_merge_strategy: "overwrite_with_compare"
-      merge_comment: "merge comment"
+      merge_comment: "merge_comment"
     steps:
       - name: Merging Branches API
         run: |
-          echo "api_key: ${{ inputs.api_key }}"
-          echo "authorization: ${{ inputs.authorization }}"
-          echo "base_branch: ${{ inputs.base_branch }}"
-          echo "compare_branch: ${{ inputs.compare_branch }}"
-          echo '${{ env.base_url }}/v3/stacks/branches_merge?base_branch=${{ inputs.base_branch }}&compare_branch=${{ inputs.compare_branch }}&default_merge_strategy=${{ env.default_merge_strategy }}&merge_comment="${{ env.merge_comment }}"'
+          echo "Merging Branches in Contentstack..."
+          # Construct the URL
+          url="${{ env.base_url }}/v3/stacks/branches_merge?base_branch=${{ inputs.base_branch }}&compare_branch=${{ inputs.compare_branch }}&default_merge_strategy=${{ env.default_merge_strategy }}&merge_comment=${{ env.merge_comment }}"
+          
+          # Execute the curl command
+          response=$(curl --location "$url" \
+            --header "api_key: ${{ inputs.api_key }}" \
+            --header "authorization: ${{ inputs.authorization }}" \
+            --header 'Content-Type: application/json' \
+            --data '{ /* Your JSON payload here if needed */ }' \
+            --write-out "%{http_code}" --silent --output /dev/null)
 
-          curl --location '${{ env.base_url }}/v3/stacks/branches_merge?base_branch=${{ inputs.base_branch }}&compare_branch=${{ inputs.compare_branch }}&default_merge_strategy=${{ env.default_merge_strategy }}&merge_comment="${{ env.merge_comment }}"' \
-          --header 'api_key: ${{ inputs.api_key }}' \
-          --header 'authorization: ${{ inputs.authorization }}' \
-          --header 'Content-Type: application/json' \
-          --data '{ }'
+          # Check for successful response
+          if [ "$response" -eq 200 ]; then
+            echo "Merge successful"
+          else
+            echo "Merge failed with status code: $response"
+            exit 1
+          fi
+
