Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,11 +39,36 @@ jobs:
       base_url: "https://eu-api.contentstack.com"
       default_merge_strategy: "overwrite_with_compare"
       merge_comment: "merge_comment"
+      MAX_BRANCHES: 5
     steps:
+      - name: Verify the branch count in Contentstack.
+        run: |
+          url="${{ env.base_url }}/v3/stacks/branches"  
+          response=$(curl --location "$url" \
+            --header "api_key: ${{ inputs.api_key }}" \
+            --header "authorization: ${{ inputs.authorization }}" \
+            --header 'Content-Type: application/json' \
+            --write-out "%{http_code}" --silent --output /dev/null)
+            
+          # Check for successful response
+          if [ "$response" -eq 200 ] || [ "$response" -eq 202 ]; then
+              echo "Check branch count successful"
+          else
+              echo "Check branch count failed with status code: $response"
+              exit 1
+          fi
+          
+          # Check if the response contains more than the specified branches
+          branch_count=$(echo "$response" | grep -o '"uid":' | wc -l)  
+          # Compare the count with the maximum
+          if [ "$branch_count" -gt $MAX_BRANCHES ]; then
+              echo "Error: More than $MAX_BRANCHES branches found. For merging branches, there should be no more than five branches."
+              exit 1
+          fi
+    
       - name: Merging Branches API
         run: |
           echo "Merging Branches in Contentstack..."
-          # Execute the curl command
           url="${{ env.base_url }}/v3/stacks/branches_merge?base_branch=${{ inputs.base_branch }}&compare_branch=${{ inputs.compare_branch }}&default_merge_strategy=${{ env.default_merge_strategy }}&merge_comment=${{ env.merge_comment }}"
           response=$(curl --location "$url" \
             --header "api_key: ${{ inputs.api_key }}" \
